<?php

namespace EpopeeBundle\Repository;

/**
 * SamochodyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SamochodyRepository extends \Doctrine\ORM\EntityRepository
{
}
