<?php

namespace EpopeeBundle\Repository;

/**
 * TesttestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TesttestRepository extends \Doctrine\ORM\EntityRepository
{
}
